version: '2'

services:
  db:
    image: postgres:9.4
    container_name: hello_phoenix_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DB: hello_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: hello_phoenix_app
    image: slawekkolodziej/hello-phoenix
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - db

volumes:
  db_data:
